
name: Deploy AWS Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Build & Deploy Lambda
        run: |
          cd backend
          npm install
          zip -r lambda.zip .
          aws s3 cp lambda.zip s3://your-s3-bucket-name/
          aws lambda update-function-code --function-name ImageService --s3-bucket your-s3-bucket-name --s3-key lambda.zip
